### 
GET http://localhost:3000 HTTP/1.1

### 
GET http://localhost:3000/cars HTTP/1.1

### 
GET http://localhost:3000/cars/2 HTTP/1.1

### 
GET http://localhost:3000/images/ HTTP/1.1

### 
POST http://localhost:3000/cars HTTP/1.1
  content-type: application/json 

  {
    "name": "Toyota Vanguard",
    "chassis": "string",
    "maker": "Toyota",
    "type": "SUV",
    "model": "string",
    "engineCode": "string",
    "mileage": "string",
    "engineSize": "string",
    "registrationYear": 2019,
    "manufacturingYear": 2019,
    "color": "Green",
    "wheelDrive": "4WD",
    "transmission": "Automatic",
    "location": "Dubai UAE",
    "steering": "string",
    "fuel": "Petrol",
    "seats": 5,
    "doors": 4,
    "weight": "string",
    "availability": "on Sale",
    "price": 2740000,
    "totalPrice": 300000
  }


### 
POST http://localhost:3000/images/uploads HTTP/1.1
  content-type: application/json

  {
    "carid": 52
  }



### 
GET http://localhost:3000/images/tesla-786c.jpg HTTP/1.1

### 
DELETE  http://localhost:3000/cars/8 HTTP/1.1
### 

DELETE  http://localhost:3000/images/18 HTTP/1.1

### 
PATCH   http://localhost:3000/cars/3 HTTP/1.1
 content-type: application/json 

  {
    "location": "Dubai UAE",
    "color":"Purple"
  }


### 
GET http://localhost:3000/reviews HTTP/1.1
  content-type: application/json


### 
POST http://localhost:3000/reviews HTTP/1.1
  content-type: application/json

  {
    "title": "How to Drive Safely",
    "description": "The car feels electric! pun intended. Best purchase I made all this month! "
  
  }

### 
PATCH  http://localhost:3000/reviews/5 HTTP/1.1
  content-type: application/json

  {
    "description": "The car feels electric "
    
  }

### 
DELETE http://localhost:3000/reviews/2 HTTP/1.1

### 
GET http://localhost:3000/messages/ HTTP/1.1
  content-type: application/json


### 
POST http://localhost:3000/messages HTTP/1.1
  content-type: application/json

  {
    "email": "dave@gmail.com",
    "message": "The car feels electric! pun intended. Best purchase I made all this month! "
  }


### 
DELETE http://localhost:3000/messages/13 HTTP/1.1

### 
GET http://localhost:3000/blogimg/tesla-5a9d.jpg HTTP/1.1
  content-type: application/json


### 
POST http://localhost:3000/blogimg/uploads HTTP/1.1
  content-type: application/json

  {
    "reviewid": 7,
    "image": " "
  
  }

### 
PATCH  http://localhost:3000/blogimg/5 HTTP/1.1
  content-type: application/json

  {
    "description": "The car feels gorgeous! pun intended. Best purchase I made all this month! "
    
  }

### 
DELETE http://localhost:3000/blogimg/3 HTTP/1.1
  
